### ISSUE TITLE
Control Click Opens Popup rather than goining to definition

### ISSUE THREAD

**Issue by maheshkurmi** [bobbylight/RSyntaxTextArea#441] opened 2022-03-16 15:05 UTC
I am using RSyntaxTexArea with "js" language support. Prior to version 3.1  **Ctrl +  Click** on any variable moved cursor to its definition, but in 3.2.0 **Ctrl+Click** opens defualt popmenu (cur, copy paste etc menu). Is it intentional or a bug?

I am using eclipse on Mac (Note: Command+Click does nothing)

**Comment by bobbylight** [comment] 2022-03-17 02:42
Interesting, I can't reproduce it on Windows, at least not with the latest build of RSTALanguageSupport (running its `DemoApp`). I'll try on a mac tomorrow.

Is the only change you made updating RSTA to 3.2.0? What version of RSTALanguageSupport are you using?

And no - that behavior would not be intentional :)

**Comment by bobbylight** [comment] 2022-03-21 03:00
On a Mac I see ctrl+click opening the popup menu *and* navigarting to/selecting the definition. I'll admit I haven't used this funcdtionality on a Mac in quite a while, so I don't know when this behavior changed. I'll look back to pre-3.1.0 releases and ses what's changed.

**Comment by maheshkurmi** [comment] 2022-03-21 08:34
It was working fine in 3.0.0 version on Mac. on 3.2.0 version when I ctrl+click it goes to definition but still shows popup.
One more issue on version 3.2.0, I have to add HyperlinkListener to the editor in order to make go to definition work. If no hyperlink listener is set it does nothing on mac and windows both, it just opens popup without navigating to definition.

**Comment by bobbylight** [comment] 2022-09-25 17:39
> One more issue on version 3.2.0, I have to add HyperlinkListener to the editor in order to make go to definition work. If no hyperlink listener is set it does nothing on mac and windows both, it just opens popup without navigating to definition.

Just a note that this particular bit was fixed in the fix for #443. The Mac-specific popup issue is still there.

**Closed** 2022-09-25 20:36 UTC
Labels: waiting-for-feedback

**Comment by bobbylight** [comment] 2022-09-25 20:50
This was fixed by changing the default hyperlink mask on Macs from `ctrl` to `cmd`. This is more natural anyway. It fixes things by avoiding a collision with another standard Mac shortcut, `ctrl + click` to open the context menu.
