### ISSUE TITLE
Gutter does not auto-size to fit line numbers greater than 99

### ISSUE THREAD

**Issue by earlhood** [bobbylight/RSyntaxTextArea#511] opened 2023-06-16 19:15 UTC
**Description**
When showing line numbers are enabled, the gutter does not auto-resize to show line numbers greater than 2 characters wide, so only the last 2 digits of the line number is visible.

**Steps to Reproduce**
Enable line numbers for RSyntaxTextArea within a RTextScrollPane.

**Expected behavior**
Gutter displaying line numbers will auto-size to fit maximum line number width.

**Actual behavior**
Gutter only shows the last 2 digits of the line number.

**Screenshots**
![Screenshot 2023-06-16 140422](https://github.com/bobbylight/RSyntaxTextArea/assets/12285664/d5625295-daa3-46f9-b32d-4251d21ed460)

**Java version**
OpenJDK 11.0.11.9-hotspot

**Additional context**
This problem at least existed in v3.2.0.  Upgraded to v3.3.3, and problem persists.

**Comment by bobbylight** [comment] 2023-07-09 18:46
@earlhood - I can't reproduce this with the RSTA demo application. Can you reproduce it there? If not, can you provide an [SSCCE](http://sscce.org/) that demonstrates the issue?

**Comment by earlhood** [comment] 2023-08-02 20:53
> @earlhood - I can't reproduce this with the RSTA demo application. Can you reproduce it there? If not, can you provide an [SSCCE](http://sscce.org/) that demonstrates the issue?

Sorry for delayed response.  I'll see if I can make a self-contained example, but it may be some time due to other work priorities.

**Comment by bobbylight** [comment] 2024-02-17 21:50
Closing as there has been no update in a few months. Please reopen if you can provide an SSCCE that demonstrates the issue!

**Closed by bobbylight** 2024-02-17 21:50 UTC
Labels: bug, waiting-for-feedback

**Comment by earlhood** [comment] 2024-04-10 20:38
[rsyntaxarea-dialog-test.tar.gz](https://github.com/bobbylight/RSyntaxTextArea/files/14937491/rsyntaxarea-dialog-test.tar.gz)

Sorry for the extremely long delay, but I think I have a self-contained example that illustrates the problem.  I have attached a sample program that uses rsyntaxtextarea in a dialog.  If you execute 'run.sh' it will compile the program and run it.  You have to use the window manager to close/exit the window as I have neutered the buttons.  The program is based on a dialog used in a product, so I had to remove references to other classes to keep the sample self-contained.
