### ISSUE TITLE
"Repaint" bug using SYNTAX_STYLE_NONE with lineWrap true

### ISSUE THREAD

**Issue by klutzer** [bobbylight/RSyntaxTextArea#108] opened 2015-02-18 01:48 UTC
This bug occur when using SYNTAX_STYLE_NONE as syntax editing style and lineWrap property as true, in a RSyntaxTextArea wrapped in RTextScrollPane.

![bug](https://cloud.githubusercontent.com/assets/10657645/6241082/f3bebc4a-b6fe-11e4-9a9c-543b76ce0bfe.png)

**Comment by klutzer** [comment] 2015-03-21 04:30
This happen with any syntax style with lineWrap activated.

**Comment by bobbylight** [comment] 2016-03-05 05:17
I cannot reproduce this.  Closing.

**Closed by bobbylight** 2016-03-05 05:17 UTC
